# -*- Mode: Python -*-

Import('env')

myenv = env.Clone()

# use custom linker script (for params and profile-stuff)
myenv['LINKFLAGS'] += ' -Wl,-T,libs/libseoul/nre/linker_' + myenv['ARCH'] + '.ld'

# we need to use whole-archive here, because the devices are not used explicitly so that the linker
# thinks he doesn't need to link them
myenv['LINKFLAGS'] += ' -Wl,--whole-archive -lseoul -Wl,--no-whole-archive'

# use a fixed link address to maximize the space for guest-memory
linkaddr = '0x60000000' if myenv['ARCH'] == 'x86_32' else '0x400000000'
myenv['LINKFLAGS'] += ' -Wl,--section-start=.init=' + linkaddr

prog = myenv.NREProgram(
    myenv, 'vancouver', Glob('*.cc'),
    cpppath = ['#libs/libseoul/include', '#libs/libseoul/nre/include'],
    fixedaddr = True
)
myenv.Depends(prog, myenv['LIBPATH'] + '/libseoul.a')
